version: 2

build:
  os: "ubuntu-lts-latest"
  tools:
    python: "3.12"

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/conf.py

# Install from pyproject.toml extras (single source of truth for deps)
python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
        - optional
